- README.md
Terminal on OS/X always does a full login for some reason so you want to use .base_profile because .bashrc will never be run. Thanks to @obastemur for pointing this out!
> OS/X wants .bash_profile not .bashrc

- thali/package.json
- thali/thalilogger.js
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/68%23discussion_r36918322%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/68%23discussion_r36918747%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/68%23discussion_r36919733%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/68%23discussion_r36924532%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/68%23discussion_r36929789%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/68%23discussion_r36929809%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/68%23discussion_r36993576%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/ …
> Added the Winston logging support

- TeamReadMe.md
Updating the team readme to include Windows instructions so that you can install PouchDB with LevelDown support.
<a href='https://www.codereviewhub.com/thaliproject/Thali_CordovaPlugin/pull/78?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/thaliproject/Thali_CordovaPlugin/pull/78'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Updating team readme with Windows pre-reqs

- plugin.xml
- src/android/java/io/jxcore/node/BtConnectorHelper.java
- src/android/java/io/jxcore/node/BtSocketDisconnectedCallBack.java
- src/android/java/io/jxcore/node/BtToRequestSocket.java
- src/android/java/io/jxcore/node/BtToServerSocket.java
- src/android/java/io/jxcore/node/BtToSocketBase.java
- src/android/java/io/jxcore/node/ConnectivityMonitor.java
- src/android/java/io/jxcore/node/JXcoreExtension.java
- src/android/java/io/jxcore/node/LifeCycleMonitor.java
- src/android/java/io/jxcore/node/StreamCopyingThread.java
- test/www/jxcore/tcpmultiplexspec.js
- thali/tcpmultiplex.js
- thali/thalireplicationmanager.js
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/69%23discussion_r36887935%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/69%23discussion_r36888127%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/69%23discussion_r36888210%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/69%23discussion_r36888421%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/69%23discussion_r36889852%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/69%23discussion_r36893413%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/69%23discussion_r36893551%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/ …
> Patching replication manager

- scripts/androidAfterPrepare.js
- scripts/package.json
The Android hook had an async step after which the process was exited. This
caused the Cordova process to exit too soon and was seen, for example, when
`cordova run android` was tried to be executed.
The `appRoot` variable is taken from the Cordova context instead of from
`__dirname` so that the path gets right even if the plugin is added via a
symbolic link.
Also removed unneeded dependency to the `lie` module.
Fixes #143.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/163)
> Don't exit the Cordova process in a hook.

- thali/install/setUpTests.sh
Stopping the iOS build so tests will run much faster and we can focus on first getting iOS working
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/184)
> Disabling building iOS

- thali/install/setUpDesktop.sh
- thali/install/setUpTests.sh
- thali/installCordovaPlugin.js
The biggest reason for doing this is that these scripts are called during the
CI build process and if the scripts don't overall exit with a non-zero exit
code, the CI thinks the build worked. The result was that even when parts of
the setup failed, the CI thought the build was successful.
Cordova plugin installation output is now logged for easier debugging.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/188)
> Exit the setup scripts if any sub-command fails.

- thali/install/install.js
- thali/install/package.json
- thali/install/remote-cache.js
A part of the installation is the download of the required version of the
JXCore Cordova plugin (currently ~90MB download) and unpacking that with jx
before adding it as Cordova plugin using Cordova commands.
This commit implements caching of the unpacked plugin folder so that the
overall installation process becomes faster. The OS temporary folder is used
for caching instead of any Thali-app folder so that full benefits of the cache
are received even if the app-folder is re-generated (this is the case with CI
scripts, for example).
This commit also adds some catches to the promise-chains so that in case of
errors, it is easier to see where the issue was.
Relates to #192.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
> Use OS temporary folder as the download cache.

- mobile_test.json
- test/TestServer/Config_PerfTest.json
- test/www/jxcore/perf_tests/SendDataConnector.js
- test/www/jxcore/perf_tests/SendDataTCPServer.js
Also, data counter variables are moved under the connection handler in
the server side, because before, the variables were "re-used" between
various peers, which made the counts invalid.
Fixes #280.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/328)
> More accuracy to the amount of data sent.

- .jscsrc
We want to exempt regex's, urls in comments and requires from the line length limit.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/368)
> Exceptions for line length

- .jshintrc
It's not good to have rules that do the same thing in both JSCS and JSHINT. It makes it really hard to deal with overrides and causes some weird behaviors.
I have removed maxline, curly because JSCS has much more flexible rules.
I got rid of sub because it's already been deprecated and we already have requireDotNotiation in JSCS
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/370)
> Remove redundant rules

- thali/install/install.js
- thali/installCordovaPlugin.js
Remove the check that was guarding against trying to install thali into a
non-supported folder.
This is done to allow the flexibility needed at thaliproject/postcardapp#85.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/364)
> Relax the installation folder requirement.

- plugin.xml
A build failure was seen with cordova-cli version < 5.3.3 so require at least
versions that were pinned in 5.3.3.
If this check fails, the fix is to upgrade Cordova on the build machine.
Fixes #350.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/363)
> Require newer Cordova versions.

- src/android/java/io/jxcore/node/ConnectionHelper.java
- src/android/java/io/jxcore/node/JXcoreExtension.java
- test/www/jxcore/PerfTest_app.js
By using a user-settable device name, it is possible to associate device logs
better with physical devices. The problem previously was especially in cases
where a test was run simultaneously with exact same device models in which
case it wasn't straightforward to do the association.
Fixes #290.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/405)
> Use user-settable device name.

- test/TestServer/PerfTestFramework.js
- test/www/jxcore/perf_tests/testFindPeers.js
The timeouts in the server were set in a way that a timeout from a previous
test got triggered when the next test was tried to be run and thus cut off
the execution of the second test.
This commit also fixed some log prints and the find peers test in case it
uses Bluetooth address lists.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/424)
> Fix an issue that prevented running two tests.

- thali/NextGeneration/thaliMobileNative.js
Specified that if connect is called a second time on the same peer ID and the first call either has resulted in a connection or hasn't completed yet then we will return an error. That way we don't have to manage a queue for connection calls at the native layer.
Fixed the link to the binding spec.
Specified that when we get too many peer Availability Changed updates that overloads our storage queue between sending batch updates to
node.js that we should drop the oldest announcements first in order to keep the queue at or below it's maximum size. Also clarified that for
incomingConnectionToPortNumberFailed only one notification in regard to any particular port's failure needs to be sent in each 100 ms window.
Specified that when the first subscription is received to networkChanged that we …
> Changes that @tobybrad and I agreed to

- test/www/jxcore/bv_tests/testThaliReplicationManager.js
- test/www/jxcore/package.json
- thali/install/setUpDesktop.sh
- thali/install/setUpTests.sh
The leveldown-mobile package is used in the primary target environment
(mobile devices) so it makes sense to do desktop testing also with that.
This also reduces the dependencies we have for the test apps.
Includes also changes to fix the build on Windows.
Fixes #422 and #394.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/502)
> Use leveldown-mobile also on desktop.

- src/android/java/org/thaliproject/p2p/ThaliPermissions.java
- test/www/js/thali_main.js
- www/android/thaliPermissions.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/537)
> In Android 6.0 adds a location permission request dialog for test apps

- test/www/jxcore/lib/testUtils.js
The PouchDB.defaults call was moved so that it gets called only once, because
otherwise, event emitters gets subscribed to many time which caused a warning
like `possible EventEmitter memory leak detected`.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/558)
> Avoid memory leak warnings

- test/www/jxcore/bv_tests/testThaliNotificationBeacons.js
- thali/NextGeneration/thaliNotificationBeacons.js
We had a spurious match during decryption that would occasionally cause
our counts to be off.
testThaliNotificationBeacons - Removed or at least better explained
magic values
thaliNotificationBeacons - Got rid of magic values and also pulled
calculating sey out of parse beacons so we only perform the ECDH
operation once per beacon string instead of once per beacon! Did the same
for the HKDF hkey value.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/560)
> Fix #539, get rid of magic values and increase perf

- test/www/jxcore/PerfTest_app.js
- test/www/jxcore/lib/thali-tape.js
- test/www/jxcore/perf_tests/PerfTestFrameworkClient.js
- thali/NextGeneration/thaliMobileNativeWrapper.js
The radio toggling at the beginning of the tests was removed as a workaround
for #563. That would be good to put back once a root cause and fix is found,
but even then, it should not be necessary to turn off radios at the end of
tests.
This was originally done for CI where devices didn't reboot in between tests,
but now devices do reboot and thus tests always start from clean radio states.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/572)
> Get rid of the radio toggling at the end of tests

- test/README.md
- test/www/jxcore/bv_tests/testPromiseQueue.js
- thali/NextGeneration/promiseQueue.js
Our promise queue used a share array for all instances, that was just a bug. Now it uses a different array of promises for each queue instance. Thanks to @vjrantal  for fixing this.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/586)
> Fix the broken queue

- .jshintrc
This is done, because latest jshint complains this as an error:
`ES5 option is now set per default`.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/590)
> Remove esversion from .jshintrc

- test/www/jxcore/bv_tests/testThaliNotificationBeacons.js
- thali/NextGeneration/notification/thaliNotificationBeacons.js
thaliNotificationBeacons -
* changes parseBeacons to return a structure with
the raw values needed to generate the artifacts required to set up a PSK
connection.
* Changed buffer to Buffer to intellij type detection would
match properly.
* generatePskIdentity and generatePskSecret are used to generate the
named values, we'll need this for the notification client.
testThaliNotificationBeacons - Added tests for the two new functions,
updated an existing test for the new response to parseBeacons and got
rid of one test that was completely redundant
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/623)
> Enabling psk

- test/www/jxcore/bv_tests/testThaliPeerPoolInterface.js
- thali/NextGeneration/thaliPeerPool/thaliPeerPoolInterface.js
@juhanak pointed out that actions that went through the pool no longer had
idempotent kill methods.
thaliPeerPoolInterface - We now remove our extra pool specific kill code
after kill is called the first time.
testThaliPeerPoolInterface - Testing that kill doesn't throw when called
multiple times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/634)
> #631 - Make kill idempotent

- appveyor.yml
And the Jx.exe version 0.3.12 which has PSK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/639)
> Validating new endpoint for Jx.exe for windows.

- test/www/jxcore/bv_tests/testThaliMobile.js
- thali/NextGeneration/thaliMobile.js
The availability of the peer was not updated properly so peer was marked
unavailable too soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/672)
> Another fix for peer unavailability watcher

- test/README.md
- test/www/jxcore/bv_tests/disabled/testIdentityExchangeEndpoint.js
- test/www/jxcore/bv_tests/disabled/testLiveIdentityExchange.js
- test/www/jxcore/bv_tests/disabled/testSmallerHashStateMachine.js
- test/www/jxcore/bv_tests/testThaliMobileNative.js
- test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js
- test/www/jxcore/lib/testUtils.js
README - Fixed a typo
testIdentityExchangeEndpoint, testLiveIdentityExchange, testSmallerHashStateMachine - Just removing calls to t.comment which we don't currently support. Changed them to t.pass. We aren't using these
tests right now but we will and I didn't want them to crash us.
testThaliMobileNative - Added a timeout to the final test so it shouldn't hang everything if it fails. I also
made the syntax error result (which usually happens when Bluetooth fails) into a recoverable error.
testThaliMobileNativeWrapper - Hardened the tests so that they would try in the face of failed connections or connections that failed mid-stream.
testUtils - Created a hardened GET function that can retry across failures
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" …
> V next tompaana multiple issues yarong

- test/www/js/thali_main.js
Removed success log on `app.js` loading failure.
Added failure log on `app.js` loading failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/845)
> #842 Removed the app.js work around

- thali/NextGeneration/thaliMobileNative.js
We originally specified that if multiconnect was called on Android then
we wouldn't return the platform error in the sync multiconnect call but
rather as an async callback. That's a lot of work to do. To simplify it
we allow the platform error to be returned on the sync multiconnect call
so android doesn't have to implement the async callback.
@chapko Please review in reviewable and either submit comments with issues or give me a :lgtm: so I can check it in. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1042)
> Return multiconnect error on Android

- test/www/jxcore/lib/wifiBasedNativeMock.js
@artemjackson please talk with @andrew-aladev as you will need to use a bunch of interfaces he knows well including setting up the new endpoints, figuring out the ACLs, etc. Also please, please, please, re-read the specs for multiConnect, multiConnectResolve, disconnect, multiConnectConnectionFailure, killConnections, etc. in thaliMobileNative and thaliMobileNativeWrapper. The mock needs to meet all those behaviors. And keep in mind that part of resolving this bug is enhancing our node tests with the right APIs to validate the mock's behavior. These tests should go right into testthaliMobileNative since these are the same tests that should be used with the native layer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Specing how we can simulate the iOS layer in the wifi mock

- thali/NextGeneration/thaliMobileNative.js
Line 58, last word was `connect` but should be `multiConnect`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1093)
> Fixed typo: 'connect' -> 'multiConnect'

- thali/NextGeneration/thaliMobile.js
For some reason I thought that Android never sends a nonTCPPeerAvailability
event wiht availability === false. It turns out we do. We have a heuristic
where if we don't discover a peer for a minute then we will announce they
have gone. For now we will just accept this heuristic at face value and
honor it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1132)
> We can get peerAvailability === false in Android

- test/www/jxcore/bv_tests/testThaliNotificationClient.js
"Bad hostname" test now checks request retries count to perform results
verification instead of 5s timeout (sometimes requests take more than 5
seconds total)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1180)
> #1059 Random `testThaliNotificationClient` test failure

- test/www/jxcore/UnitTest_app.js
- test/www/jxcore/bv_tests/testThaliManagerCoordinated.js
- test/www/jxcore/bv_tests/testThaliMobileNative.js
- thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js
- thali/NextGeneration/thaliManager.js
- thali/NextGeneration/utils/pouchDBGenerator.js
UnitTest_app.js - These changes make Bluebird happy, otherwise it will
complain about "a promise was created in a handler but was not returned
from it"
testThaliManagerCoordinated - Linting
thaliSendNotificationBasedOnReplication - Added an assert on one of
our constructor arguments, covered a theoretical edge case where we
could end up with a negative time value. Clarified that one of the functions
handles an arg different than stated.
thaliManager - Linting
pouchDBGeneratior - Linting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1248)
> Mostly linting, maybe fixing

- test/TestServer/HttpServer.js
- test/TestServer/TestFramework.js
- test/TestServer/index.js
- test/www/jxcore/UnitTest_app.js
- test/www/jxcore/bv_tests/testThaliMobile.js
- test/www/jxcore/lib/CoordinatedClient.js
- test/www/jxcore/lib/CoordinatedTape.js
- test/www/jxcore/lib/SimpleTape.js
- test/www/jxcore/lib/thaliTape.js
- test/www/jxcore/runCoordinatedTests.js
- test/www/jxcore/runTests.js
- test/www/jxcore/spawnTest.js
We have both `require` (old variant) and `spawn` working: `require` for ios (for now) and `spawn` for desktop and android.
Closes #1228.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1279)
> Spawning test in separate process

- lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift
Not a real leak of memory - advertiser will be disposed after 30 sec. But it breaks our logic for `stopAdvertising`. After call of this function all existing advertiser should be stopped and destroyed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1395)
> memory leak fix

- test/www/jxcore/lib/wifiBasedNativeMock.js
This is related to #1072. Mock was not updated to use random SSDP_NT value and native tests could  fail if they had started in the same network simultaneously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1424)
> Use random SSDP_NT for mock

- test/README.md
- test/TestServer/index.js
- test/www/jxcore/UnitTest_app.js
- test/www/jxcore/lib/CoordinatedClient.js
- test/www/jxcore/lib/parsePlatformArg.js
- test/www/jxcore/lib/wifiBasedNativeMock.js
- test/www/jxcore/runCoordinatedTests.js
- test/www/jxcore/runTests.js
Closes #1172.
I have to admit it is very ugly solution. Partially because we have multiple entry points for running tests (there is `jx runCoordinated.js`, `jx runTests.js`, and `jx UnitTest_app.js` which are depend on each other) and side effects in the core modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1430)
> Enable coordination server to run multiple networkTypes

- test/www/jxcore/lib/testUtils.js
- test/www/jxcore/meta_tests/testPouchDBAgent.js
- thali/NextGeneration/replication/thaliReplicationPeerAction.js
Closes #730.
Our pouch `5.4.5` is fine. It has some kind of `isPlainObject` and this function bypasses our agent.
@chapko found a [commit](https://github.com/pouchdb/pouchdb/commit/a3736c7d455b5a0133fc594a395e1800d90ac010), it adds this function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1466)
> Added PouchDB agent test

- src/android/java/io/jxcore/node/OutgoingSocketThread.java
- src/android/java/io/jxcore/node/SocketThreadBase.java
- test/www/jxcore/bv_tests/testThaliMobileNative.js
- test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js
- test/www/jxcore/lib/CoordinatedClient.js
- thali/NextGeneration/makeIntoCloseAllServer.js
SocketThreadBase - Turns out that the logic that got checked in could end up setting buffers to zero
because the Bluetooth socket get size calls could return 0. For now I decided to just remove the dynamic
size setting to simplify things. This should hopefully fix Android.
testThaliMobileNative - We have a condition where we could test something after we have called t.end but
this is necessary because our peer might be done with the test but the other might not. So now the test
will only cause a failure if it actually fails in which case we should fail.
testThaliMobileNativeWrapper - In addition to an identical issue to the one described above we also had tests
that were written before the skip functionality so I fixed that. Also some of the test names were so similar it
made doing …
> #1588 Fixing up Android buffer problem and failing tests

- test/README.md
- thali/install/install.js
- thali/install/setUpDesktop.sh
README - Updating to the actual validateBuildEnvironment script that we now run
install - Turns out I used the syntax for build-extras.gradle instead of gradle.properties and didn't realize it because I still had the environment variables defined.
setUpDesktop - The logic we were using which would use the global variable if already defined otherwise it would set it doesn't work in the case of NVM_NODEJS_ORG_MIRROR if someone is using NVM which also sets this variable. Since NVM is more common than needing to change this location when doing our build I decided to revert that change and just overwrite the variable when we are doing a build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> #1632 - Fixing broken build

- build.sh
- test/www/jxcore/installCustomPouchDB.js
setUpDesktop.sh runs `node installCustomPouchDB.js` before dependencies
are installed. Since we are using pure node we can just drop
object-assign dependency and use native implementation
> Fix "module not found" error during build

- test/www/jxcore/bv_tests/testThaliMobile.js
This is based on timer, because of possible race condition in case when we try to restart ThaliMobile (call stop and start) whenever any error occurs. Currently this test is at most ran 5 times, which I believe is more than enough. However, sometimes my Nexus can get into very sad state, that it is really really slow and doesn't make any connections, so it is still possible that this test will fail after 5 retries, but it clearly tells us that nexus bluetooth is pretty bad.
Fix for thaliproject/Thali_CordovaPlugin#1594 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1715)
> Fix for 'test for data corruption'

- thali/install/SSDPReplacer/hook.js
- thali/install/SSDPReplacer/plugin.xml
It was a reason for many false test failures on local devices in native mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1776)
> Fix replacer hook

- test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js
- test/www/jxcore/bv_tests/testThaliManagerCoordinated.js
- test/www/jxcore/bv_tests/testThaliMobile.js
- thali/NextGeneration/replication/thaliReplicationPeerAction.js
1. Disabled PouchDB checkpoints plugin tests (thaliproject/Thali_CordovaPlugin#1741 PR fixes it)
2. "Fixed" thaliManagerCoordinated test failures caused by performance issues (#1618)
3. Changed a bit thaliManagerCoordinated test logic, so now test repeat tests start watching for db changes at the beginning of the test.
4. Minor improvements (arbitrary number of 'test repeat write' test, optional debugging logs)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1794)
> Fix tests for iOS and Android

- test/www/jxcore/bv_tests/testThaliManager.js
- test/www/jxcore/bv_tests/testThaliManagerCoordinated.js
- test/www/jxcore/bv_tests/testThaliNotificationClient.js
- test/www/jxcore/bv_tests/testThaliPeerPoolDefault.js
- test/www/jxcore/bv_tests/testThaliPeerPoolOneAtATime.js
- test/www/jxcore/bv_tests/testThaliPullReplicationFromNotification.js
- thali/NextGeneration/notification/thaliNotificationClient.js
- thali/NextGeneration/replication/thaliPullReplicationFromNotification.js
- thali/NextGeneration/thaliManager.js
- thali/NextGeneration/thaliPeerPool/thaliPeerAction.js
- thali/NextGeneration/thaliPeerPool/thaliPeerPoolDefault.js
- thali/NextGeneration/thaliPeerPool/thaliPeerPoolInterface.js
- thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js
This is a **breaking change**. If you use custom thaliPeerPool implementation you have to throw errors from the `enqueue` method instead of returning them. 
Fixes #1813.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1816)
> #1813 Fix inconsistent ThaliPeerPool enqueue API

- test/www/jxcore/bv_tests/testSSDPServer.js
- thali/NextGeneration/thaliWifiInfrastructure.js
Previously `bssidName:<MAC address>` → `bssidName:null` was considered as simple BSSID change and wifiInfrastructure was restarting ssdp client and server. SSDP start always fails when bssidName is null because it means that we are not connected to any access point and couldn't advertise anything.
In reality bssid change from/to null should be handled the same way as enabling/disabling WiFi on device.
Fixes #1823.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1826)
> Fix wifi network changes handling

- test/www/jxcore/bv_tests/testPromiseQueue.js
- thali/NextGeneration/promiseQueue.js
1. Fix unhandled rejections when function passed into enqueue method throws an error.
2. Refactor internal implementation so it create only one promise when someone enqueues new executor. Also it does not build entire promise chain after calling `enqueue` but rather chains next promise right before the next task starts.
3. Tests, of course.
Fixes #1044
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1848)
> Refactor promiseQueue implementation

- test/www/jxcore/bv_tests/testHttp.js
- test/www/jxcore/bv_tests/testThaliMobileNative.js
Also contains fix for #1864 . These tests were failing on desktop because there is one particular test which is fired only on iOS devices, but in teardown we always try to kill http server, even if it was not started. So the fix is to pass additional argument to `makeIntoCloseAllServer`, which causes that if fail while closing server occur it is does not cause tests to fail.
If it comes to fix for #1866 , it looks like the functions which are used in `Can shift data` and `Can shift data via parallel connections` were removed after merge with master. The fix contains these functions restored which makes tests pass on desktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/tha …
> Fix failing Can shift data test on dekstop

- test/www/jxcore/bv_tests/testThaliMobile.js
First of all, before starting this test we need to make sure that ThaliMobile is started. 
Otherwise, `networkChangedNonTCP` events will be filtered out.
Based on test assumptions that we discover 1 peer via WiFi and 1 peer via MPCF,
we can safely assume that phone is connected to access point so the `bbsidName` field
is set to some non null value. This is because `networkChangedValue` with `bssidName` set to null is treated same as WiFi off.
See #1500 and #1707 for details.
Also, since this scenario assume that after disabling WiFi `peerAvailabilityChanged` event would
be fired twice, we need to increase `availibilityHandler` calls limit by one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fix failing test on iOS devices #1871

- test/www/jxcore/bv_tests/testThaliManagerCoordinated.js
- test/www/jxcore/bv_tests/testThaliReplicationPeerAction.js
- test/www/jxcore/bv_tests/testThaliReplicationPeerActionCoordinated.js
- thali/NextGeneration/replication/thaliPullReplicationFromNotification.js
- thali/NextGeneration/replication/thaliReplicationPeerAction.js
- thali/NextGeneration/thaliManager.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1876)
> Provide remote db name for ThaliReplicationPeerAction during runtime #1873

- thali/install/validateBuildEnvironment.js
Updated validateBuildEnvironment.js script according to changes on the CI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1952)
> Updated versions of 3rd party libraries

- test/www/jxcore/bv_tests/testThaliReplicationPeerAction.js
- thali/NextGeneration/replication/thaliReplicationPeerAction.js
This will allow to provide custom No activity timeout value when starting Replication Action directly from policy manager, which should solve some issues with slow radios such as Bluetooth especially on Android devices, see #1961.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1962)
> Add possibility to provide custom No activity timeout value to ReplicationAction
