README.md, sample/www/index.html, sample/www/jxcore/test/thaliscenarios.js
This updates us to use JX Core as our PC based installer, specifies the use of Tape and how to run the desktop tests, fixes some old paths, etc.
=> Bunch of minor updates

thali/thalicryptomanager.js
I got rid of some extraneous comments and made it clearer what the hash function does. Note that these are "comments" so I haven't tested that they don't break something. :)
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/srichal%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11357884%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/58%23issuecomment-127776960%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-04T22%3A11%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11357884%3Fv%3D3%22%2C%20%22html …
=> Code review comments

readme.md
<a href='https://www.codereviewhub.com/thaliproject/Thali_CordovaPlugin/pull/85?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/thaliproject/Thali_CordovaPlugin/pull/85'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> We don't need the find instruction anymore

test/www/jxcore/runTests.js, test/www/jxcore/testThaliCryptoManager.js
Also fixed problem with picking up the test file that was
causing one of the crypto tests to fail.
<a href='https://www.codereviewhub.com/thaliproject/Thali_CordovaPlugin/pull/90?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/thaliproject/Thali_CordovaPlugin/pull/90'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Thanks to Oguz automated test runner works

scripts/androidAfterPrepare.js
<a href='https://www.codereviewhub.com/thaliproject/Thali_CordovaPlugin/pull/86?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/thaliproject/Thali_CordovaPlugin/pull/86'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix to support the recent updates in Cordova regarding the minSDK

readme.md
<a href='https://www.codereviewhub.com/thaliproject/Thali_CordovaPlugin/pull/92?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/thaliproject/Thali_CordovaPlugin/pull/92'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fixing minor bug in install from new version of Cordova

TeamReadMe.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/100)
=> Updating btconnectorlib2 location

TeamReadMe.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/103)
=> Manually handling NPM version

src/ios/MultipeerConnectivity/THEMultipeerClient.m, src/ios/MultipeerConnectivity/THEMultipeerSocketRelay.m
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/104)
=> Story 0 tobybrad

TeamReadMe.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/111)
=> Updating build commands

TeamReadMe.md, thali/install/install.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/117)
=> Point NPM at master branch!

thali/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/119)
=> Updating npm version number

TeamReadMe.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/121)
=> Updating how to do releases

TeamReadMe.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/203)
=> Updating publish instructions

plugin.xml, src/ios/MultipeerConnectivity/THEMultipeerClient.h, src/ios/MultipeerConnectivity/THEMultipeerClient.m, src/ios/MultipeerConnectivity/THEMultipeerClientSession.h, src/ios/MultipeerConnectivity/THEMultipeerClientSession.m, src/ios/MultipeerConnectivity/THEMultipeerClientSocketRelay.m, src/ios/MultipeerConnectivity/THEMultipeerClientSocketRelayDelegate.h, src/ios/MultipeerConnectivity/THEMultipeerPeerSession.h, src/ios/MultipeerConnectivity/THEMultipeerPeerSession.m, src/ios/MultipeerConnectivity/THEMultipeerServer.h, src/ios/MultipeerConnectivity/THEMultipeerServer.m, src/ios/MultipeerConnectivity/THEMultipeerSession.h, src/ios/MultipeerConnectivity/THEMultipeerSession.m, src/ios/MultipeerConnectivity/THEMultipeerSessionDelegate.h, src/ios/MultipeerConnectivity/THEMultipeerSocketRelay.m, src/ios/THEAppContext.h, src/ios/THEAppContext.m, test/www/jxcore/bv_tests/testThaliReplicationManager.js, thali/install/prePublishThaliCordovaPlugin.js, thali/package.json
Reverts thaliproject/Thali_CordovaPlugin#272
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/286)
=> Revert 952b9b6416567822e2e3b3a4141a5a0f3d8c83eb

plugin.xml, src/ios/MultipeerConnectivity/THEMultipeerClient.h, src/ios/MultipeerConnectivity/THEMultipeerClient.m, src/ios/MultipeerConnectivity/THEMultipeerClientSession.h, src/ios/MultipeerConnectivity/THEMultipeerClientSession.m, src/ios/MultipeerConnectivity/THEMultipeerClientSocketRelay.m, src/ios/MultipeerConnectivity/THEMultipeerClientSocketRelayDelegate.h, src/ios/MultipeerConnectivity/THEMultipeerDiscoveryDelegate.h, src/ios/MultipeerConnectivity/THEMultipeerPeerSession.h, src/ios/MultipeerConnectivity/THEMultipeerPeerSession.m, src/ios/MultipeerConnectivity/THEMultipeerServer.h, src/ios/MultipeerConnectivity/THEMultipeerServer.m, src/ios/MultipeerConnectivity/THEMultipeerSession.h, src/ios/MultipeerConnectivity/THEMultipeerSession.m, src/ios/MultipeerConnectivity/THEMultipeerSocketRelay.m, src/ios/THEAppContext.h, src/ios/THEAppContext.m, test/www/jxcore/bv_tests/testThaliReplicationManager.js, thali/package.json
See PR 272 for reviews on this PR. *THIS* PR exists to retarget the incorrectly targeted PR 272.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/288)
=> Issue 263 to story001

test/TestServer/PerfTestFramework.js, test/TestServer/index.js, test/www/jxcore/lib/thali-tape.js, test/www/jxcore/perf_tests/testReConnect.js, test/www/jxcore/perf_tests/testSendData.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/339)
=> Small fixes to test results reporting

thali/install/install.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/344)
=> Update to jxcore-cordova release 0.0.8.

src/android/java/io/jxcore/node/BtConnectorHelper.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/334)
=> Fixed bug #300: We need to beef up our logging of exceptions

thali/NextGeneration/thaliMobileNative.js, thali/NextGeneration/wifiBasedNativeMock.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/352)
=> Story 03 yarong 249

.gitignore, doc/api/testServer.md, test/README.md, test/TestServer/IPAddressToFile.js, test/TestServer/generateServerAddress.js, test/www/jxcore/PerfTest_app.js, test/www/jxcore/lib/thali-tape.js, test/www/jxcore/readme.md
This was done to fix compatibility with `jx package` which doesn't work with
.json files.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/360)
=> Make server address a proper node module.

src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/ConnectionStatusListener.java, src/android/java/io/jxcore/node/IncomingSocketThread.java, src/android/java/io/jxcore/node/JXcoreExtension.java, src/android/java/io/jxcore/node/OutgoingSocketThread.java, src/android/java/io/jxcore/node/SocketThreadBase.java, src/android/java/io/jxcore/node/StreamCopyingThread.java, thali/install/setUpTests.sh
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/374)
=> Story 001 tompaana 371

.jscsrc, .jshintrc
We changed .jshintrc in master but we didn't RI to story 001. This fixes that.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/380)
=> RI'ing .jshintrc from master

test/www/jxcore/bv_tests/testLargerHashStateMachine.js, test/www/jxcore/bv_tests/testSmallerHashStateMachine.js
Fixing the merge errors from P4merge for Issue #383.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/384)
=> Closing Issue #383

src/android/JXcore.gradle, src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/ConnectionStatusListener.java, src/android/java/io/jxcore/node/ConnectivityMonitor.java, src/android/java/io/jxcore/node/IncomingSocketThread.java, src/android/java/io/jxcore/node/JXcoreExtension.java, src/android/java/io/jxcore/node/OutgoingSocketThread.java, src/android/java/io/jxcore/node/SocketThreadBase.java, src/android/java/io/jxcore/node/StreamCopyingThread.java, test/TestServer/Config_PerfTest.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/388)
=> Story 001 tompaana 387

src/android/JXcore.gradle, src/android/java/io/jxcore/node/ConnectionHelper.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/389)
=> Story 001 tompaana 354

readme.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/391)
=> update suggested jxcore version

test/TestServer/ResultsProcessor.js, test/www/jxcore/PerfTest_app.js, test/www/jxcore/meta_tests/testPerfTestFramework.js, test/www/jxcore/meta_tests/testPerfTestFrameworkClient.js, test/www/jxcore/meta_tests/testResultsProcessor.js, test/www/jxcore/perf_tests/PerfTestFrameworkClient.js, test/www/jxcore/perf_tests/SendDataConnector.js, test/www/jxcore/perf_tests/SendDataTCPServer.js, test/www/jxcore/perf_tests/testSendData.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/421)
=> Fix an inaccuracy with data rate reporting

src/android/JXcore.gradle, src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/ConnectionStatusListener.java, src/android/java/io/jxcore/node/SocketThreadBase.java, thali/readme.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/426)
=> Story 001 tompaana 406

doc/api/thalireplicationmanager.md
ThaliReplicationManager.start was incorrectly documented.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/433)
=> fix API docs for Replication Manager

test/TestServer/TestFramework.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/436)
=> Fix running tests when `userConfig` isn't given.

TeamReadMe.md
Fixes #425.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/437)
=> Update release instructions.

build.sh, test/www/jxcore/bv_tests/testMultiplex.js
Commented out one test that must be fixed separately, because that one hangs
forever and thus prevents the build from proceeding.
Fixes #386.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/438)
=> Run desktop tests in CI.

thali/install/install.js
Fixes #435.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/463)
=> Update to jxcore-cordova 0.1.0.

test/www/jxcore/bv_tests/mockmobile.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/268)
=> Localhost GetDocumentsPath method update in mockmobile.js - fixes #233

thali/NextGeneration/thaliWifiInfrastructure.js
The original language I submitted made literally no sense. Hopefully this version will be slightly more sensible.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/470)
=> Fix messed up SSDP binding language

test/www/jxcore/bv_tests/mockmobile.js
Reverts thaliproject/Thali_CordovaPlugin#268
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/494)
=> Revert "Localhost GetDocumentsPath method update in mockmobile.js - fixes #233"

test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, test/www/jxcore/package.json, thali/NextGeneration/thaliWifiInfrastructure.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/496)
=> More Wifi infrastructure features

LICENSE, build.sh, plugin.xml, scripts/androidBeforeCompile.js, src/android/JXcore.gradle, src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/JXcoreExtension.java, src/android/java/io/jxcore/node/PeerAndConnectionModel.java, src/android/project.properties
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/503)
=> V next tompaana 486

appveyor.yml, build.sh, thali/NextGeneration/thaliMobile.js, thali/install/setUpTests.sh
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/506)
=> Address test setup issue

test/README.md
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/510)
=> Adds guidance for Windows users

test/www/jxcore/bv_tests/testThaliNotificationBeacons.js, thali/NextGeneration/hkdf.js, thali/NextGeneration/thaliNotificationBeacons.js
testThaliNotificationBeacons - JSCS/JShint fixes as well as a new test
that showed that we weren't properly parsing the beacons.
hkdf - JSCS/JSHint fixes
thaliNotificationBeacons - JSCS/JShint fixes, factored out the function
to create public key hashes and some other random stuff.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/516)
=> Fixes from review

build.sh
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/518)
=> Update Cordova only in CI

thali/install/install.js
Fixes #522.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/524)
=> Update to jxcore-cordova 0.1.1

build.sh, plugin.xml, readme.md, src/android/java/org/thaliproject/p2p/ThaliPermissions.java, www/android/thaliPermissions.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/515)
=> Request and Check Permissions in Android #412

build.sh, test/www/jxcore/runCoordinatedTests.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/525)
=> Run coordinated desktop tests in CI

TeamReadMe.md, test/TestServer/UnitTestFramework.js, test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, test/www/jxcore/lib/testUtils.js, test/www/jxcore/lib/thali-tape.js, test/www/jxcore/runCoordinatedTests.js, thali/NextGeneration/thaliMobile.js, thali/NextGeneration/thaliMobileNative.js, thali/NextGeneration/thaliMobileNativeWrapper.js, thali/NextGeneration/thaliWifiInfrastructure.js, thali/install/setUpDesktop.sh, thali/install/setUpTests.sh
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/530)
=> Network change behavior for thaliWifiInfrastructure

thali/NextGeneration/makeIntoCloseAllServer.js
Fixes #542.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/543)
=> Fix closing sockets when server closed

test/README.md, test/www/jxcore/PerfTest_app.js, test/www/jxcore/UnitTest_app.js, test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/bv_tests/testThaliMobileNative.js, test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, test/www/jxcore/lib/testUtils.js, test/www/jxcore/lib/thali-tape.js, test/www/jxcore/lib/wifiBasedNativeMock.js, test/www/jxcore/package.json, test/www/jxcore/perf_tests/PerfTestFrameworkClient.js, test/www/jxcore/readme.md, test/www/jxcore/runCoordinatedTests.js, test/www/jxcore/runTests.js, thali/NextGeneration/thaliMobile.js, thali/NextGeneration/thaliMobileNativeWrapper.js, thali/NextGeneration/thaliWifiInfrastructure.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/540)
=> Better desktop testing support with improved mocking

test/README.md, test/www/jxcore/bv_tests/testThaliNotificationBeacons.js, thali/NextGeneration/thaliNotificationBeacons.js
README - Just pointing out to avoid sudo if possible
testThaliNotificationBeacons - Changes notificationBeacons and long to
lower case variables since they are not constructors. Changed the constants
to use the values exposed by ThaliNotificationBeacons. Cleaned up and
expanded bad arguments test. Fixed timing tests so they now realize that
we pass in time until expiration, not absolute time, when creating
beacons. Add time test to take into account fuzzing
thaliNotificationBeacons - Made constants into exported values so we can
use them for testing. Changed one_day to show how it was derived. Adding in
fuzzing of expiration date. Changed seconds to milliseconds in
generatePremableAndBecaons and fixed the code so now the value is treated
as the expiration interval and not an absolute …
=> Crypto fixes

src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/ConnectionModel.java, src/android/java/io/jxcore/node/ConnectivityInfo.java, src/android/java/io/jxcore/node/IncomingSocketThread.java, src/android/java/io/jxcore/node/JXcoreThaliCallback.java, src/android/java/io/jxcore/node/OutgoingSocketThread.java, src/android/java/io/jxcore/node/SocketThreadBase.java, src/android/java/io/jxcore/node/StreamCopyingThread.java, test/www/jxcore/PerfTest_app.js, test/www/jxcore/lib/testUtils.js, thali/NextGeneration/thaliMobileNativeWrapper.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/550)
=> Minor fixes for Tomi's consideration

src/ios/JXcoreExtension.m, src/ios/THEAppContext.h, src/ios/THEAppContext.m, test/www/jxcore/UnitTest_app.js, test/www/jxcore/lib/wifiBasedNativeMock.js, thali/NextGeneration/thaliMobileNative.js, thali/NextGeneration/thaliMobileNativeWrapper.js, thali/NextGeneration/thaliWifiInfrastructure.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/544)
=> didRegisterToNative specification and implementation on iOS

test/www/jxcore/bv_tests/testThaliTCPServersManager.js, thali/NextGeneration/makeIntoCloseAllServer.js, thali/NextGeneration/tcpServersManager.js, thali/thalilogger.js
testThaliTCPServersManager - lint fixes
makeIntoCloseAllServer - Some linting and making sure that close got called
first and THEN we close the connections and THEN call the callback.
tcpServersManager - Linting
thalilogger - Linting
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/564)
=> Mostly linting

test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/bv_tests/testThaliMobileNative.js, test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, test/www/jxcore/lib/wifiBasedNativeMock.js, thali/NextGeneration/thaliConfig.js, thali/NextGeneration/thaliMobile.js, thali/NextGeneration/thaliWifiInfrastructure.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/562)
=> More features to thaliMobile

test/www/jxcore/bv_tests/testThaliMobileNative.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/573)
=> Fix unreliability in coordinated desktop test run

test/TestServer/UnitTestFramework.js, test/www/jxcore/lib/thali-tape.js, test/www/jxcore/runCoordinatedTests.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/575)
=> Catch errors in setup/teardown

test/www/jxcore/bv_tests/testPromiseQueue.js, thali/NextGeneration/promiseQueue.js
Includes a test that would fail without the fix.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/581)
=> Fix an issue in the promise queue

test/www/jxcore/bv_tests/testThaliNotificationServer.js, test/www/jxcore/lib/httpTester.js, thali/NextGeneration/notification/thaliNotificationServer.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/585)
=> ThalinotificatioServer for review

test/www/jxcore/bv_tests/testThaliPeerAction.js, test/www/jxcore/bv_tests/testThaliPeerPoolInterface.js, thali/NextGeneration/thaliPeerPool/thaliPeerAction.js, thali/NextGeneration/thaliPeerPool/thaliPeerPoolDefault.js, thali/NextGeneration/thaliPeerPool/thaliPeerPoolInterface.js
Still need to do thaliPeerPoolDefault
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/588)
=> thaliPeerAction & thaliPeerPoolInterface

plugin.xml, src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/HandshakeHelper.java, src/android/java/io/jxcore/node/SocketThreadBase.java, test/www/jxcore/bv_tests/testThaliMobileNative.js, test/www/jxcore/lib/wifiBasedNativeMock.js
Tested/verified to work.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/577)
=> Handshake implementation

src/android/JXcore.gradle, src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/StartStopOperation.java, src/android/java/io/jxcore/node/StartStopOperationHandler.java
The major part of this fix was implemented to the Bluetooth connector library. This PR is almost only about making the plug-in to use the latest version of the library.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/600)
=> Fix for issue #47: Outgoing connections can now be initiated even when we are not listening for incoming connections.

test/www/jxcore/bv_tests/testThaliPeerDictionary.js, thali/NextGeneration/notification/thaliNotificationAction.js, thali/NextGeneration/notification/thaliPeerDictionary.js
PeerDictionary implementation and just small changes to thaliNotificationAction.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/596)
=> PeerDictionary and minor changes to thaliNotificationAction

src/android/JXcore.gradle, src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/JXcoreExtension.java, src/android/java/io/jxcore/node/StartStopOperation.java, src/android/java/io/jxcore/node/StartStopOperationHandler.java, thali/NextGeneration/thaliMobileNative.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/615)
=> Fixed the state error and updated the Bluetooth connector library version

test/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/625)
=> Added instructions how to test the Doze and App Standby mode on Android

test/README.md, test/www/jxcore/meta_tests/testUnitTestFramework.js, test/www/jxcore/runCoordinatedTests.js
This adds a --filter argument that lets one specify a single file for the coordinator to run instead of all of them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/627)
=> Run one test file through the coordinator at a time

thali/install/install.js, thali/install/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/630)
=> Use a custom build of jxcore-cordova

test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, test/www/jxcore/lib/wifiBasedNativeMock.js, thali/NextGeneration/mux/createPeerListener.js, thali/NextGeneration/thaliMobileNativeWrapper.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/640)
=> Get basic end to end connections working

appveyor.yml
See document [distribute](https://github.com/thaliproject/jxbuild/blob/master/distribute.md) for URLs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/644)
=> URL isn't the proper one as it will be deprecated to a different url

thali/NextGeneration/thaliMobile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/650)
=> Adds a typedef for peerAvailabilityChanged event's object

test/TestServer/UnitTestConfig.js, test/TestServer/UnitTestFramework.js, test/TestServer/index.js, test/www/jxcore/bv_tests/testTests.js, test/www/jxcore/lib/thali-tape.js, test/www/jxcore/meta_tests/testUnitTestFramework.js, test/www/jxcore/runCoordinatedTests.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/656)
=> Support passing data in coordinated tests

test/www/jxcore/bv_tests/testThaliMobile.js, thali/NextGeneration/thaliMobile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/676)
=> Peer unavailable event when port changes

test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, thali/NextGeneration/thaliWifiInfrastructure.js
Relates to #678.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/680)
=> Avoid emitting peer unavailable from self

test/www/jxcore/bv_tests/testThaliNotificationBeacons.js, thali/NextGeneration/notification/thaliNotificationBeacons.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/688)
=> SHA256 the PSK Identity

test/www/jxcore/runCoordinatedTests.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/690)
=> Fixes coordinated test colors

thali/install/setUpDesktop.sh
We now need two environment variables to be set in order to download
a custom version of NPM and point JXcore at it. So I added these two
variables to setUpDesktop.sh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/710)
=> #708 - Fix environment variables

thali/install/install.js, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/713)
=> Fix for #711 - added jxcore url to configuration file

build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/736)
=> Remove Cordova update during build

src/android/test/com/test/thalitest/ThaliTestSuite.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/748)
=> updeted test suite

src/android/test/io/jxcore/node/ConnectivityMonitorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/749)
=> UT Extended timeouts in ConnectivityMonitorTest

src/android/java/io/jxcore/node/JXcoreExtension.java, test/www/js/thali_main.js, test/www/jxcore/UnitTest_app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/753)
=> V next jareksl 555

src/android/java/io/jxcore/node/ConnectivityMonitor.java, test/www/jxcore/UnitTest_app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/787)
=> Added missing method (added in the version 0.3.2 of the BTLibrary)

test/www/jxcore/UnitTest_app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/792)
=> Switched off execution of the node tests.

mobile_test.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/793)
=> Changed build target (only android)

thali/install/setUpTests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/794)
=> Commented out compilation for iOS

build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/796)
=> Commented out copy of app for iOS

test/www/jxcore/UnitTest_app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/802)
=> Leave the test app running even if UT are failing

test/www/jxcore/UnitTest_app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/803)
=> finish testing before the node part

test/www/jxcore/UnitTest_app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/804)
=> V next jareksl 555 clean

scripts/androidBeforeCompile.js, src/android/test/com/test/thalitest/RegisterExecuteUT.java, test/www/jxcore/UnitTest_app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/806)
=> Few fixes after the CR

build.sh, mobile_test.json, thali/install/setUpTests.sh
Due to issues in CI regarding building iOS app we need to temporarily disable the iOS build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/801)
=> Commented out ios build specific code for CI (#798)

src/android/java/io/jxcore/node/IncomingSocketThread.java, src/android/test/com/test/thalitest/RegisterExecuteUT.java, src/android/test/io/jxcore/node/IncomingSocketThreadMock.java, src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, src/android/test/io/jxcore/node/OutgoingSocketThreadMock.java, src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, src/android/test/io/jxcore/node/StreamCopyingThreadTest.java, test/www/jxcore/bv_tests/testNativeTestMethod.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/813)
=> V next mlesnic 777

test/www/jxcore/bv_tests/testPouchDBGenerator.js, test/www/jxcore/lib/testUtils.js, test/www/jxcore/package.json, thali/NextGeneration/utils/pouchDBGenerator.js, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/795)
=> Fixed default adapter and test of pouchdb generator

test/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/816)
=> Updated README

build.sh, thali/install/setUpTests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/832)
=> Removed parameter UT

scripts/androidBeforeCompile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/809)
=> Remove not needed // jscs:enable jsDoc

build.sh, scripts/androidBeforeCompile.js, src/android/test/com/test/thalitest/RegisterExecuteUT.java, src/android/test/com/test/thalitest/ThaliTestRunner.java, src/android/test/io/jxcore/node/ConnectionHelperTest.java, src/android/test/io/jxcore/node/ConnectionModelTest.java, src/android/test/io/jxcore/node/ConnectivityMonitorTest.java, src/android/test/io/jxcore/node/IncomingSocketThreadMock.java, src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, src/android/test/io/jxcore/node/LifeCycleMonitorTest.java, src/android/test/io/jxcore/node/ListenerOrIncomingConnectionTest.java, src/android/test/io/jxcore/node/OutgoingSocketThreadMock.java, src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, src/android/test/io/jxcore/node/SocketThreadBaseTest.java, src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java, src/android/test/io/jxcore/node/StartStopOperationTest.java, src/android/test/io/jxcore/node/StreamCopyingThreadTest.java, test/www/jxcore/UnitTest_app.js, test/www/jxcore/bv_tests/testNativeMethod.js, test/www/jxcore/runTests.js, thali/package.json
PR that implements #777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/850)
=> #777 Additional native unit tests

thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/886)
=> #866 Updated jxcore-cordova version to 0.1.2b

test/TestServer/npm-shrinkwrap.json, test/www/jxcore/npm-shrinkwrap.json, thali/install/npm-shrinkwrap.json, thali/npm-shrinkwrap.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/905)
=> #758 Added shrinkwrap files

test/TestServer/TestDevice.js, test/TestServer/TestFramework.js, test/TestServer/UnitTestConfig.js, test/TestServer/UnitTestFramework.js, test/TestServer/index.js, test/www/jxcore/UnitTest_app.js, test/www/jxcore/lib/thaliTape.js, test/www/jxcore/runTests.js
Change for #847
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/918)
=> Handling variable number of devices in CI and failing native tests

readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/890)
=> #541 Updated readme with the latest JXCore installation info

build.sh, src/android/test/com/test/thalitest/RegisterExecuteUT.java, test/www/jxcore/UnitTest_app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/924)
=> rename JavaScript method ExecuteNativeTests into executeNativeTests

thali/NextGeneration/thaliManager.js
Closes #952
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/954)
=> Fixed stopping default pool

lib/ios/ThaliCore/.swiftlint.yml, lib/ios/ThaliCore/ThaliCore/Core/ApplicationStateNotificationsManager.swift, lib/ios/ThaliCore/ThaliCore/Core/PeerIdentifier.swift, lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/Advertiser.swift, lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/Browser.swift, lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/BrowserManager.swift, lib/ios/ThaliCore/ThaliCoreTests/AppStateNotificationsManagerTests.swift, lib/ios/ThaliCore/ThaliCoreTests/BrowserManagerTests.swift, lib/ios/ThaliCore/ThaliCoreTests/PeerDiscoveryTests.swift, lib/ios/ThaliCore/ThaliCoreTests/String+Random.swift, lib/ios/ThaliCore/ThaliCoreTests/ThaliSingleInstanceTests.swift, src/ios/AppContext.swift, src/ios/AppContextTests.swift
Uploading changes in linter config.
Fixing current linter issues as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/965)
=> #906 Choose Swift codestyle guide for ThaliCore

build.sh, lib/ios/ThaliCore/ThaliCore/Core/PeerIdentifier.swift, lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/BrowserManager.swift, src/ios/AppContext.swift, src/ios/AppContextTests.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/945)
=> added peer generation to peerAvailabilityChanged

build.sh, test/www/jxcore/package.json, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1013)
=> fix: Cannot find module 'child-process-promise' on CI in vNext #1012

thali/NextGeneration/thaliMobileNativeWrapper.js
Please give me a LGTM if this fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1049)
=> Fixed a typo

src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/StartStopOperationHandler.java, src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1026)
=> Fixed race condition from tearDown in StartStopOperationTest

test/www/jxcore/UnitTest_app.js
See discussion in: https://github.com/thaliproject/CI/issues/80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1133)
=> Ensure native tests failure is correctly reported

test/www/jxcore/runTests.js, thali/install/setUpTests.sh, thali/install/setUpThaliTestIds.js
Closes #1144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1147)
=> Fixed desktop platform name and commented replacing ios header

thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1159)
=> Fixed disk_size error

test/TestServer/utils/Promise.js, test/www/jxcore/UnitTest_app.js, test/www/jxcore/lib/CoordinatedClient.js, test/www/jxcore/lib/CoordinatedTape.js, test/www/jxcore/lib/utils/Promise.js, test/www/jxcore/runTests.js, thali/install/utils/Promise.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1154)
=> Fixed logging to device screen

test/TestServer/HttpServer.js, test/www/jxcore/runCoordinatedTests.js, test/www/jxcore/runTests.js, thali/NextGeneration/thaliConfig.js, thali/NextGeneration/thaliWifiInfrastructure.js, thali/install/setUpThaliTestIds.js
Closes #1072
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1148)
=> SSDP updater for runTests and runCoordinated

test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/package.json, thali/NextGeneration/thaliMobile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1176)
=> #1167 Fixed ThaliMobile network type to use global network type if presented

test/TestServer/Socket.js, test/TestServer/TestDevice.js, test/TestServer/UnitTestFramework.js, test/www/jxcore/lib/CoordinatedClient.js, test/www/jxcore/lib/SimpleTape.js, test/www/jxcore/meta_tests/testCanBeSkipped.js
Closes #1149.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1160)
=> Simple skip test function

test/www/jxcore/UnitTest_app.js, test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js
Closes #1161 and #1178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1181)
=> #1161 and #1178 Fixed PouchDB test directory

test/www/jxcore/lib/CoordinatedClient.js
Closes #1191.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1198)
=> Fixed failed error in CoordinatedClient

test/www/jxcore/lib/CoordinatedClient.js, test/www/jxcore/package.json, thali/ThaliLogger.js
Closes #1179.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1204)
=> Upgraded socket.io-client to the recent version

thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js, thali/NextGeneration/utils/pouchDBGenerator.js
Related to #970. This wont close issue. We need to investigate the reason of assertion failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1211)
=> Workaround for pouchdb error handlers

test/www/jxcore/bv_tests/testThaliManager.js, test/www/jxcore/bv_tests/testThaliManagerCoordinated.js, thali/NextGeneration/thaliManager.js
Closes #1009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1218)
=> networkType for thali manager

test/TestServer/HttpServer.js, test/TestServer/TestDevice.js, test/TestServer/TestFramework.js, test/TestServer/UnitTestFramework.js, test/www/jxcore/UnitTest_app.js, test/www/jxcore/lib/CoordinatedClient.js, test/www/jxcore/lib/CoordinatedTape.js, test/www/jxcore/lib/SimpleTape.js, test/www/jxcore/runTests.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1223)
=> Fix wrong test report results for native and node tests

thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js
Closes #1230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1236)
=> #1230 Increase max number of peers to notify from 10 to 15

readme.md, test/README.md, thali/NextGeneration/thaliWifiInfrastructure.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1239)
=> Some instructions on using Thali

src/android/java/io/jxcore/node/StreamCopyingThread.java, src/android/test/build-extras.gradle, src/android/test/com/test/thalitest/RegisterExecuteUT.java, src/android/test/com/test/thalitest/ThaliTestRunner.java, src/android/test/io/jxcore/node/CITestClass.java, src/android/test/io/jxcore/node/ConnectionHelperTest.java, src/android/test/io/jxcore/node/ConnectionModelTest.java, src/android/test/io/jxcore/node/ConnectivityMonitorTest.java, src/android/test/io/jxcore/node/IncomingSocketThreadMock.java, src/android/test/io/jxcore/node/IncomingSocketThreadMockWithLatch.java, src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, src/android/test/io/jxcore/node/JXcoreThaliCallbackMock.java, src/android/test/io/jxcore/node/LifeCycleMonitorTest.java, src/android/test/io/jxcore/node/ListenerMock.java, src/android/test/io/jxcore/node/ListenerOrIncomingConnectionTest.java, src/android/test/io/jxcore/node/OutgoingSocketThreadMock.java, src/android/test/io/jxcore/node/OutgoingSocketThreadMockWithLatch.java, src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, src/android/test/io/jxcore/node/SocketThreadBaseMock.java, src/android/test/io/jxcore/node/SocketThreadBaseTest.java, src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java, src/android/test/io/jxcore/node/StartStopOperationTest.java, src/android/test/io/jxcore/node/StreamCopyingThreadTest.java
Fixed IncomingSocketThreadTest and OutgoingSocketThreadTest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1225)
=> Android tests from vNext

build.sh, thali/install/setUpTests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1251)
=> update build script according to the changes in iOS branch

test/www/jxcore/UnitTest_app.js, test/www/jxcore/bv_tests/testNativeMethod.js, test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, test/www/jxcore/lib/testUtils.js, test/www/jxcore/lib/wifiBasedNativeMock.js, test/www/jxcore/runTests.js, thali/NextGeneration/thaliMobile.js, thali/NextGeneration/thaliMobileNativeWrapper.js, thali/NextGeneration/utils/platform.js
This is `superbranch_android` branch which contains only #1185 PR and fix for #1255. Since we are submitting all the android node changes into iOS branch instead of android branch I suggest to simply merge it into iOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1256)
=> Merge wifiBasedNativeMock into iOS branch

build.sh, test/www/jxcore/runCoordinatedTests.js, thali/install/setUpDesktop.sh, thali/install/setUpTests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1254)
=> switch coordination server from jx into node

build.sh, src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, test/www/jxcore/bv_tests/testLocalSeqManagerCoordinated.js, test/www/jxcore/bv_tests/testThaliReplicationPeerAction.js, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1260)
=> update Jxcore and enable Coordinated seq test and Make sure docs replicate

lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/AdvertiserManagerTests.swift, src/ios/AppContext.swift, src/ios/AppContextTests.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1241)
=> fixing AppContext discovering itself.

test/TestServer/index.js, test/www/jxcore/runCoordinatedTests.js, test/www/jxcore/runTests.js
Closes #1282.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1285)
=> Require instead of spawn for android

thali/NextGeneration/thaliMobileNative.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1289)
=> removed deprecated specs

readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1311)
=> Create "Useful commands to run Android apps via command line" guide

test/README.md, thali/install/install.js, thali/install/postPublishThaliCordovaPlugin.js, thali/install/prePublishThaliCordovaPlugin.js, thali/install/setUpDesktop.sh, thali/install/setUpTests.sh, thali/install/utils/child_process.js, thali/installCordovaPlugin.js, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1200)
=> Move off JXcore where we can

thali/NextGeneration/thaliMobileNative.js
thaliMobileNative - Defining that network state must also check for SSID
and adding a method to turn WiFi on and off.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1315)
=> Wifi Managing

test/www/jxcore/bv_tests/testThaliMobile.js, thali/NextGeneration/thaliConfig.js, thali/NextGeneration/thaliMobile.js, thali/NextGeneration/thaliMobileNative.js, thali/NextGeneration/thaliMobileNativeWrapper.js, thali/NextGeneration/utils/common.js
This PR contains logic related to the new "peerAvailabilityChanged" event format (#899).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1328)
=> #899 Update thaliMobile for WiFi and Android (peerAvailabilityChanged)

test/www/jxcore/UnitTest_app.js
Main issue is #1353.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1354)
=> Disable node tests for iOS

lib/ios/ThaliCore/ThaliCore/SocketConnection/AdvertiserRelay.swift, lib/ios/ThaliCore/ThaliCore/SocketConnection/BrowserRelay.swift, lib/ios/ThaliCore/ThaliCore/SocketConnection/TCPListener.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/TCPListenerTests.swift, lib/ios/ThaliCore/ThaliCoreTests/Utils/MultipeerConnectHelper.swift
Main issue is #1355.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1357)
=> Fixing testStopListeningForConnectionsReleasesPort

test/www/jxcore/Battery_app.js, test/www/jxcore/package.json
Closes #1292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1326)
=> Battery test app

thali/install/SSDPReplacer/Promise.js, thali/install/SSDPReplacer/hook.js, thali/install/SSDPReplacer/package.json, thali/install/SSDPReplacer/plugin.xml, thali/install/SSDPReplacer/process.js, thali/install/setUpTests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1338)
=> SSDP replacer as cordova plugin

test/www/jxcore/bv_tests/testThaliMobileNative.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1359)
=> skip `Connect port dies if not connected to in time` for iOS

test/www/jxcore/bv_tests/testThaliMobileNativeDiscoveryCoordinated.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1378)
=> skipped no peer discovery for iOS #1323

thali/install/cordova-hooks/ios/before_plugin_install.js, thali/install/install.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1371)
=> remove unnecessary iOS cordova hook logic

thali/install/install.js, thali/install/utils/child_process.js, thali/installCordovaPlugin.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1380)
=> Use updated version exec with live streaming of stdout, stderr

thali/install/install.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1381)
=> Disable non-local installation and throw an error in other case

lib/ios/ThaliCore/ThaliCore/Utils/NetworkReachability/NetworkReachability.h, lib/ios/ThaliCore/ThaliCore/Utils/NetworkReachability/NetworkReachability.m, src/ios/AppContext.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1324)
=> New WiFi functionality (getting SSID)

thali/install/SSDPReplacer/Promise.js, thali/install/SSDPReplacer/hook.js
Closes #1392.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1393)
=> Fixed default directory for SSDP replacer

lib/ios/ThaliCore/ThaliCore/Core/Peer.swift, lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/BrowserManager.swift, lib/ios/ThaliCore/ThaliCoreTests/CoreTests/PeerTests.swift, lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/BrowserManagerTests.swift, src/ios/AppContext.swift, src/ios/AppContextTests.swift, src/ios/JXcoreExtension.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1301)
=> fixing native code to pass thaliMobileNative.js

thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1402)
=> Updated BtLib version

build.sh, src/ios/AppContext.swift, src/ios/JXcoreExtension.m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1367)
=> fixed failing Get same port when trying to connect multiple times on iOS

readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1409)
=> update README.md to fix #1336

src/ios/AppContext.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1419)
=> swift linter fix

build.sh, src/ios/AppContextTests.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1420)
=> App context test fix

test/README.md, test/www/jxcore/bv_tests/testThaliManagerCoordinated.js, test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/lib/testUtils.js, test/www/jxcore/runCoordinatedTests.js
README - Lint
testThaliManagerCoordinated - Switching back to default pool manager
testThaliMobile - Enabling tests to run in CI since all devices are now
on public Wifi, this should be interesting. Also added test to detect
data corruption in a non-trivial scenario. Also fixed a test which wasn't
dealing well with zombies.
testUtils - Added utils to handle PUT requests
runCoordinatedTests - Linting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1427)
=> Testing for corrupt data

src/android/java/io/jxcore/node/StreamCopyingThread.java, test/README.md, test/TestServer/HttpServer.js, test/TestServer/TestFramework.js, test/TestServer/UnitTestFramework.js, test/TestServer/index.js, test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/lib/CoordinatedClient.js, test/www/jxcore/lib/testUtils.js, test/www/jxcore/lib/wifiBasedNativeMock.js, test/www/jxcore/runTests.js, thali/NextGeneration/mux/thaliTcpServersManager.js, thali/NextGeneration/thaliMobile.js, thali/install/setUpDesktop.sh
testThaliMobile - Hardened data corruption test so it can handle zombie
availability announcements
thaliTcpServersManager - Making sure we can see when someone has
intentionally terminated an outgoing connection.
All other files are just linting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1434)
=> README - Added a note

test/www/jxcore/package.json, thali/package.json
Closes #1431.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1451)
=> Updated node ssdp

thali/install/validateBuildEnvironment.js
- add ANDROID_HOME check
- update validateBuildEnvironment.js to handle crashes better
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1436)
=> fix iOS build that was broken by validateBuildEnvironment.js

thali/install/setUpTests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1465)
=> fix invalid name of app.js in setUpTests.sh

thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1478)
=> Updated BtLib to 0.3.5

test/www/jxcore/installCustomPouchDB.js, test/www/jxcore/package.json
Closes #1480.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1481)
=> Updated express version and commit id

build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1484)
=> fix CI build fails #1463

test/www/jxcore/bv_tests/testCreatePeerListener.js, thali/NextGeneration/mux/createPeerListener.js
Closes #1473.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1474)
=> Fixed this socket is closed

build.sh, test/www/jxcore/bv_tests/testThaliNotification.js, test/www/jxcore/bv_tests/testThaliNotificationClient.js, test/www/jxcore/bv_tests/testThaliPeerPoolOneAtATime.js, test/www/jxcore/installCustomPouchDB.js, test/www/jxcore/lib/testUtils.js, thali/NextGeneration/mux/createPeerListener.js, thali/NextGeneration/mux/thaliTcpServersManager.js, thali/NextGeneration/notification/thaliNotificationClient.js, thali/NextGeneration/replication/thaliReplicationPeerAction.js, thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js, thali/NextGeneration/thaliWifiInfrastructure.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1483)
=> Master yarong 1446 retries fix

src/android/java/io/jxcore/node/ConnectivityMonitor.java, src/android/java/io/jxcore/node/JXcoreExtension.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1320)
=> added ssid name parameter to node call

thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1501)
=> update jxcore cordova plugin to 0.1.6

build.sh, lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/Advertiser.swift, lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/Browser.swift, lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/BrowserManager.swift, lib/ios/ThaliCore/ThaliCoreTests/CoreTests/AppStateNotificationsManagerTests.swift, lib/ios/ThaliCore/ThaliCoreTests/CoreTests/AtomicTests.swift, lib/ios/ThaliCore/ThaliCoreTests/CoreTests/PeerTests.swift, lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/AdvertiserManagerTests.swift, lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/AdvertiserTests.swift, lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/BrowserManagerTests.swift, lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/BrowserTests.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/AdvertiserRelayTests.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/BrowserRelayTests.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/RelayTests.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/SessionTests.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/TCPClientTests.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/TCPListenerTests.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/TCPServerMock.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/VirtualSocketBuilderTests.swift, lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, lib/ios/ThaliCore/ThaliCoreTests/Utils/MultipeerConnectHelper.swift, lib/ios/ThaliCore/ThaliCoreTests/Utils/StringRandomTests.swift, thali/install/setUpTests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1339)
=> Fix issues with native unit tests on iOS.

test/www/jxcore/lib/CoordinatedClient.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1522)
=> Improve CoordinatedClient logging

readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1536)
=> update using Thali instructions #1221 #1250

build.sh, readme.md, thali/install/include.sh/build-dep.sh, thali/install/install.js, thali/install/setUpDesktop.sh, thali/install/setUpTests.sh, thali/install/validateBuildEnvironment.js, thali/package.json
update node to 6.9.1
update npm to 3.10.8
update brew to 1.1.*
update jxcore to 0.3.1.6
update androidBuildTools to 25.0.0
update androidSupportLibraries to 40.0.0
update jxcoreCordova to 0.1.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1523)
=> update thali development environment

src/android/java/io/jxcore/node/ConnectionHelper.java, thali/NextGeneration/thaliMobileNativeWrapper.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1541)
=> Added emitting  of the incomingConnectionToPortNumberFail event

src/android/java/io/jxcore/node/ConnectionHelper.java, thali/NextGeneration/thaliMobileNativeWrapper.js
Reverts thaliproject/Thali_CordovaPlugin#1541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1552)
=> Revert "Added emitting  of the incomingConnectionToPortNumberFail event"

build.sh, src/android/java/io/jxcore/node/JXcoreExtension.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1550)
=> Removed pleaseConnect

thali/install/setUpDesktop.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1555)
=> fix setUpDesktop.sh

src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/SocketThreadBase.java, src/android/test/io/jxcore/node/ListenerMock.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1559)
=> Fixed cast exception. Implemented proper logic for 1507 issue

thali/NextGeneration/thaliManager.js
Closes #1553.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1558)
=> Updated salti for attachments

readme.md, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1570)
=> update JXcore to 0.3.1.7

plugin.xml, readme.md, thali/install/cordova-hooks/android/after_plugin_install.js
update cordova-android to 6.0.0
update cordova-ios to 4.3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1566)
=> update cordova iOS and Android engines

build.sh, src/android/test/com/test/thalitest/ThaliTestRunner.java, src/android/test/io/jxcore/node/ConnectionHelperTest.java, src/android/test/io/jxcore/node/ConnectivityMonitorTest.java, src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java, src/android/test/io/jxcore/node/StreamCopyingThreadTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1576)
=> Refactored tests

test/www/jxcore/bv_tests/testSSDPServer.js
Closes #1345.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1571)
=> Added nodessdp restart test

test/www/jxcore/lib/CoordinatedClient.js
Closes #1350.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1563)
=> Added unexpected error handler

test/www/jxcore/UnitTest_app.js
Implements thaliproject/Thali_CordovaPlugin#1604
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1608)
=> change devices tests network type from Wi-Fi to Native

build.sh, thali/install/setUpDesktop.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1575)
=> Tweak build scripts for other OSes

test/www/jxcore/bv_tests/testLocalSeqManager.js, test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/bv_tests/testThaliPullReplicationFromNotificationCoordinated.js, test/www/jxcore/bv_tests/testThaliReplicationPeerAction.js
Related issues:
- #1531
- #1613
- #1618
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1623)
=> Disable tests failing on iOS

src/android/java/io/jxcore/node/JXcoreExtension.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1639)
=> Removed unnecessary import

build.sh, src/android/java/io/jxcore/node/ConnectionData.java, src/android/java/io/jxcore/node/SocketThreadBase.java, src/android/java/io/jxcore/node/StreamCopyingThread.java, src/android/test/io/jxcore/node/StreamCopyingThreadTest.java
from bt or TCP recieved data
incoming or outgoing connection
peer id
data amount
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1444)
=> added logs

readme.md, thali/install/validateBuildEnvironment.js, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1647)
=> JXcore 0.3.1.8

plugin.xml
update cordova-ios to 4.3.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1633)
=> upgrade cordova engines

test/www/jxcore/bv_tests/testThaliPullReplicationFromNotificationCoordinated.js, test/www/jxcore/lib/CoordinatedClient.js, test/www/jxcore/package.json
Closes #1613.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1648)
=> Fixed t.sync by using relative path

src/android/java/io/jxcore/node/JXcoreExtension.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1651)
=> Fixed peer generation

test/www/jxcore/bv_tests/testThaliMobileNativeDiscoveryCoordinated.js
I have just reverted test to the [`217da85`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/217da85a30ece5133725f208c83e9e0b1ce3c46d/test/www/jxcore/bv_tests/testThaliMobileNativeDiscoveryCoordinated.js) commit and removed test timeout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1667)
=> #1665 Fix "Test 'update peer discovery 1' fails on desktop and phones in iOS branch"

test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, thali/NextGeneration/thaliConfig.js, thali/NextGeneration/thaliWifiInfrastructure.js
Closes #1631.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1669)
=> added an ssdp ip option

test/www/jxcore/bv_tests/testLocalSeqManager.js
Related to thaliproject/Thali_CordovaPlugin#1618
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1678)
=> #1531 Increase LocalSeqManager timers for iOS devices

test/www/jxcore/installCustomPouchDB.js
Closes #1679.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1681)
=> Added beta to custom pouchdb release

build.sh, test/www/jxcore/bv_tests/testNativeMethod.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1684)
=> Skip 'onPeerDiscovered calls jxcore' and 'onPeerLost calls jxcore' on iOS

test/www/jxcore/lib/wifiBasedNativeMock.js
thaliproject/Thali_CordovaPlugin#1489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1696)
=> Changed wifiPeerAvailabilityChanged in wifiBasedNativeMock

test/www/jxcore/bv_tests/testThaliReplicationPeerActionCoordinated.js, test/www/jxcore/lib/testUtils.js
Closes #1595.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1689)
=> Added retry for runTestOnAllParticipants

src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/JXcoreExtension.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1699)
=> Add listening to connectivity events when app starts

test/www/jxcore/UnitTest_app.js, test/www/jxcore/lib/testUtils.js, test/www/jxcore/runTests.js
Closes #1673.
Client will be disqualified from test server if it has no ability to enable bluetooth.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1697)
=> Moved network check into has required hardware

test/www/jxcore/bv_tests/testThaliManagerCoordinated.js
Related to #1687.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1694)
=> Increased timeouts for test write

src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/JXcoreExtension.java, src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1695)
=> Refactor start/stop operation test

src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/JXcoreExtension.java, src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java
Improved readability of the tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1685)
=> Refactor incoming and outgoing socket thread tests

test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js, test/www/jxcore/lib/wifiBasedNativeMock.js
thaliproject/Thali_CordovaPlugin#1079
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1706)
=> Add test for bad parameters in multiConnect, edit wifiBasedNativeMock

lib/ios/ThaliCore/ThaliCore/SocketConnection/GCDAsyncSocket/GCDAsyncSocket.h, lib/ios/ThaliCore/ThaliCore/SocketConnection/GCDAsyncSocket/GCDAsyncSocket.m, thali/install/setUpTests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1702)
=> Updating GCDAsyncSocket with new version

test/www/jxcore/lib/testUtils.js
Closes #1713.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1714)
=> Fixed task cancel

test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/lib/CoordinatedClient.js, test/www/jxcore/lib/CoordinatedTape.js
Closes #1530. Related to https://github.com/thaliproject/CI/issues/97.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1712)
=> Fixed test server reconnection

test/www/jxcore/bv_tests/testThaliNotificationAction.js, test/www/jxcore/bv_tests/testThaliNotificationClient.js, thali/NextGeneration/notification/thaliNotificationClient.js, thali/NextGeneration/notification/thaliPeerDictionary.js
Closes #1687.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1708)
=> Fixed dictionary and related tests

test/www/jxcore/bv_tests/testThaliMobile.js, thali/NextGeneration/thaliMobile.js, thali/NextGeneration/thaliMobileNativeWrapper.js
This PR fixes only part of the #1500.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1707)
=> Fix race conditions in networkChanged event handling

src/android/java/io/jxcore/node/JXcoreExtension.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1718)
=> Remove unnecessary getInstance call

test/TestServer/TestDevice.js, test/TestServer/UnitTestFramework.js, test/www/jxcore/lib/CoordinatedClient.js
Closes #1614.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1716)
=> Fixed test server custom error

test/www/jxcore/bv_tests/testThaliMobileNative.js, test/www/jxcore/bv_tests/testThaliMobileNativeAndroid.js, test/www/jxcore/lib/thaliMobileNativeTestUtils.js
Closes #1374.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1710)
=> Fixed reconnect after close

src/android/java/io/jxcore/node/JXcoreExtension.java, src/android/test/com/test/thalitest/RegisterExecuteUT.java, test/www/jxcore/bv_tests/testNativeMethod.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1726)
=> Fix onPeerLost test

build.sh, test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/bv_tests/testThaliMobileNativeAndroid.js, test/www/jxcore/lib/testUtils.js, thali/NextGeneration/thaliMobile.js
Fixes #1725 and #1731.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1735)
=> Fix failing test (#1725 and #1731)

.eslintrc, test/www/jxcore/bv_tests/testThaliMobile.js, thali/NextGeneration/thaliMobile.js
Clean up thaliMobile.js and testThaliMobile.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1746)
=> Add docs, fix lint warnings

src/android/java/io/jxcore/node/JXcoreExtension.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1747)
=> Add null sending in JSON between Android and Node

test/www/jxcore/bv_tests/testThaliMobile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1760)
=> Disable android-only tests on iOS platform

test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js, test/www/jxcore/lib/wifiBasedNativeMock.js, thali/NextGeneration/thaliMobileNative.js
Fixes #1749.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1756)
=> #1749 Update multiConnect invalid syncValue handling

thali/install/validateBuildEnvironment.js, thali/package.json
Fix for #1762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1763)
=> Update Android tools versions

readme.md, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1775)
=> Update jxcore to 0.3.1.9

src/android/java/io/jxcore/node/JXcoreExtension.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1769)
=> Add check if radio is on before starting the advertising and listening

test/www/jxcore/package.json, thali/package.json
Forever agent with thaliproject/forever-agent#1 fix.
Fixes #1771 and #1744
See details in the [comments to #1744](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1744#issuecomment-277996480)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1777)
=> Update forever-agent to the newest version

readme.md, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1796)
=> Update jxcore to 0.3.1.10

test/www/jxcore/bv_tests/testSSDPServer.js, test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, thali/NextGeneration/thaliWifiInfrastructure.js, thali/NextGeneration/utils/common.js
Fixes #1500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1773)
=> #1500 Fix wifi mode advertising/discovering after connecting to another WiFi access point

src/android/java/io/jxcore/node/ConnectionHelper.java, src/android/java/io/jxcore/node/ConnectionModel.java
The initialization of the thread was moved before adding the thread to collection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1801)
=> Fix null pointer exception.

src/android/java/build-extras.gradle, src/android/java/io/jxcore/node/ConnectionModel.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1807)
=> Rollback to java 1.6 version

.eslintrc.js, thali/NextGeneration/notification/thaliNotificationClient.js, thali/NextGeneration/replication/thaliReplicationPeerAction.js, thali/NextGeneration/thaliMobileNative.js, thali/NextGeneration/thaliMobileNativeWrapper.js, thali/NextGeneration/thaliWifiInfrastructure.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1815)
=> Eslint: ignore too long valid jsdoc lines

test/www/jxcore/bv_tests/testThaliMobileNative.js
#1778 
The timeout of 1s also worked in 3 consecutive tests, set 5s just in case to avoid test fails. Need to investigate the reasons why MPCF advertises the peer **after stopAdvertisingPeer()** is called
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1829)
=> Fix “Can connect to a remote peer” test

thali/NextGeneration/thaliMobileNativeWrapper.js
I have no idea how I missed it during code review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1842)
=> Revert disconnect changes

test/www/jxcore/bv_tests/testThaliMobileNative.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1838)
=> There is no unit tests for discoveryAdvertisingStateUpdateNonTCP of thaliMobileNative.js #868

lib/ios/Cartfile.resolved, thali/install/ios/nativeInstaller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1839)
=> Simplify and improve build process for iOS

src/ios/AppContext.swift, src/ios/Testing/AppContextTests.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1846)
=> Put NSNull instead of nil to didResolveMultiConnectWithSyncValue method #1843

thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1851)
=> Update compile sdk version to 25

test/www/jxcore/bv_tests/testThaliMobileNative.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1854)
=> IOS native can't handle parallel connection from node #1845 node

test/www/jxcore/bv_tests/testHttp.js, test/www/jxcore/bv_tests/testThaliMobileNative.js, thali/NextGeneration/thaliMobileNativeWrapper.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1855)
=> Http tests

test/www/jxcore/bv_tests/testThaliMobile.js, test/www/jxcore/bv_tests/testThaliMobileNative.js, test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1858)
=> Can shift data via parallel connections fails on desktop #1857

test/www/jxcore/bv_tests/testThaliMobileNative.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1865)
=> Fixed missing closing parenthesis.

thali/install/validateBuildEnvironment.js, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1889)
=> Update jxcore-cordova to 0.1.12 version

test/www/jxcore/bv_tests/testLocalSeqManager.js, test/www/jxcore/bv_tests/testThaliManagerCoordinated.js, test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, test/www/jxcore/bv_tests/testThaliReplicationPeerAction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1886)
=> Enable tests that were disabled due to #1600, #1618 and #1767

test/www/jxcore/bv_tests/testTests.js, test/www/jxcore/lib/SimpleTape.js
Added skip function allowing to use test.skip() for tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1911)
=> Added skip function to allow a test to be skipped over

test/www/jxcore/bv_tests/testThaliMobileNative.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1916)
=> Fix calling t.end before assertion in testThaliMobileNative

readme.md, thali/install/validateBuildEnvironment.js, thali/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1959)
=> Update jxcore-cordova to 0.1.14 version, update readme.md
